import "./globals.css";

import { Inter } from "next/font/google";

import type { Metadata } from "next";
import { ReactNode } from "react";
import { RootLayout } from "@/layouts/RootLayout";
import { AntdRegistry } from "@ant-design/nextjs-registry";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Layout = ({
  children,
}: Readonly<{
  children: ReactNode;
}>) => (
  <html lang="en">
    <RootLayout>
      <body className={inter.className}>
        <AntdRegistry>{children}</AntdRegistry>
      </body>
    </RootLayout>
  </html>
);

export default Layout;
